services:
  app:
    image: docker.io/naumenkomaks/ai-squad:latest
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "${PORT:-3000}:3000"
    networks:
      - backend

  nginx:
    image: nginx:alpine
    restart: unless-stopped
    depends_on:
      - app
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./nginx/auth:/etc/nginx/auth:ro
    networks:
      - backend

networks:
  backend:
    driver: bridge 